_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 1
                - 16
                - 23
                - 55
            "4": 3.12.4
            "5": 0.19.10
            "8":
                - 5
            "12": 0.19.10
            "13": darwin-arm64
batch_size:
    value: 32
epochs:
    value: 30
lr:
    value: 0.0001
